<?php
/**
 * Created by PhpStorm.
 * User: ShonnZong
 * Date: 2019/9/26
 * Time: 10:56
 */

namespace app\api\controller\User;


use app\common\controller\Api;

/**
 * Class User 会员接口
 * @package app\api\controller\User
 */
class User extends Api
{
    protected $noNeedLogin = ['login', 'mobilelogin', 'register', 'resetpwd', 'changeemail', 'changemobile', 'third'];
    protected $noNeedRight = '*';

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 会员中心
     */
    public function index()
    {
        $this->success('', ['welcome' => $this->auth->nickname]);
    }

    /**
     * 会员登录
     * @param string $account 账号
     * @param string $password 密码
     */
    public function login()
    {
        $post_data = $this->getPostData();
        if (!isset($post_data['account']) || !isset($post_data['password'])) {
            $this->error(__('Invalid parameters'));
        }
        $ret = $this->auth->login($post_data['account'], $post_data['password']);
        if ($ret) {
            $data = ['userInfo' => $this->auth->getUserinfo()];
            $this->success(__('Logged in successful'), $data);
        } else {
            $this->error($this->auth->getError());
        }
    }
}